decision-service-a:
  applicationName: decision-service-dev
  containerImage:
    repository: nginx
  service:
    type: NodePort
github-service:
  applicationName: github-service
  containerImage:
    repository: tpayne666/webrestapi
  containerPorts:
    http:
      port: 80
  service:
     type: LoadBalancer
     ports:
      app:
        port: 8080
        targetPort: http