decision-service-a:
  applicationName: decision-service-dev
  containerImage:
    repository: nginx
  service:
    type: NodePort
github-service:
  applicationName: github-service
  containerImage:
    repository: tpayne666/webrestapi
  service:
    type: LoadBalancer