apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo-app
  namespace: demo-app
spec:
  releaseName: demo-app-prod
  chart:
    git: https://github.com/tpayne/kubernetes-examples.git
    path: YAML/GitOps/AzureArc/configs/charts/demo-app
    ref: main

