apiVersion: v2
name: dev
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
dependencies:
  - name: wscs-deployment
    version: "0.1.0"
    repository: "https://raw.githubusercontent.com/tpayne/kubernetes-examples/main/Helm/wscs-deployment"
  - name: wsnodejs-deployment
    version: "0.1.0"
    repository: "https://raw.githubusercontent.com/tpayne/kubernetes-examples/main/Helm/wsnodejs-deployment"
  - name: wscs-b-deployment
    version: "0.1.0"
    repository: "https://raw.githubusercontent.com/tpayne/kubernetes-examples/main/Helm/wscs-b-deployment"
  - name: wsnodejs-b-deployment
    version: "0.1.0"
    repository: "https://raw.githubusercontent.com/tpayne/kubernetes-examples/main/Helm/wsnodejs-b-deployment"
  - name: jenkinscd-framework-deployment
    version: "0.1.0"
    repository: "https://raw.githubusercontent.com/tpayne/kubernetes-examples/main/Helm/jenkinscd-framework-deployment"
  - alias: decision-service-a
    name: k8s-service
    version: "0.2.12"
    repository: "https://helmcharts.gruntwork.io"
  - alias: decision-service-b
    name: k8s-service
    version: "0.2.12"
    repository: "https://helmcharts.gruntwork.io"