decision-service-a:
  applicationName: decision-service-dev
  containerImage:
    repository: nginx
    tag: 1.14.2
  service:
    type: NodePort
decision-service-b:
  applicationName: decision-service-test
  containerImage:
    repository: nginx
    tag: 1.14.2
  service:
    type: NodePort