# Release stack to deploy on target
# Service SBOM for demo  
decision-service-a:
  containerImage:
    tag: "1.14.2"
github-service:
  containerImage:
    tag: "baa79c0"
wsnodejs-deployment:
  containerImage:
    tag: "latest"
wscs-deployment:
  containerImage:
    tag: "latest"
